DROP DATABASE IF EXISTS LIBRARY;

CREATE DATABASE LIBRARY;

USE LIBRARY;

DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER` (
	`ME_ID`	VARCHAR(12) PRIMARY KEY	NOT NULL,
	`ME_PW`	VARCHAR(16) NOT	NULL,
	`ME_NAME`	CHAR(8) NOT	NULL,
	`ME_NUM`	VARCHAR(13) UNIQUE NOT	NULL,
	`ME_AUTHORITY`	ENUM("USER","ADMIN") DEFAULT "USER" NOT	NULL,
	`ME_CAN_RENT`	ENUM("Y","N") DEFAULT "Y" NOT	NULL,
	`ME_CAN_RENT_DATE`	DATE	NULL,
	`ME_NO_RENT`	INT DEFAULT 0 NOT	NULL,
	`ME_DEL`	ENUM("Y","N") DEFAULT "Y" NOT	NULL
);

DROP TABLE IF EXISTS `BOOK`;

CREATE TABLE `BOOK` (
	`BO_CODE`	CHAR(6) PRIMARY KEY	NOT NULL,
	`BO_TITLE`	VARCHAR(100) NOT	NULL,
	`BO_AUTHOR`	VARCHAR(50) NOT	NULL,
	`BO_PUBLISHER`	VARCHAR(20) NOT	NULL,
	`BO_DEL`	ENUM("Y","N") DEFAULT "N" NOT	NULL,
	`BO_RENT`	ENUM("Y","N") DEFAULT "N" NOT	NULL,
	`BO_CA_CODE`	CHAR(3)	NOT NULL
);

DROP TABLE IF EXISTS `CATEGORY`;

CREATE TABLE `CATEGORY` (
	`CA_CODE`	CHAR(3) PRIMARY KEY	NOT NULL,
	`CA_NAME`	VARCHAR(4) UNIQUE NOT	NULL
);

DROP TABLE IF EXISTS `RENT`;

CREATE TABLE `RENT` (
	`RE_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`RE_RENT_DATE`	DATETIME DEFAULT CURRENT_TIMESTAMP NOT	NULL,
	`RE_STATE`	CHAR(2) DEFAULT "대여" NOT	NULL,
	`RE_RETURN_DATE`	DATETIME	NULL,
	`RE_DUE_DATE`	DATETIME NOT	NULL,
	`RE_ME_ID`	VARCHAR(12)	NOT NULL,
	`RE_BO_CODE`	CHAR(6)	NOT NULL
);

ALTER TABLE `RENT` ADD CONSTRAINT `FK_MEMBER_TO_RENT_1` FOREIGN KEY (
	`RE_ME_ID`
)
REFERENCES `MEMBER` (
	`ME_ID`
);

ALTER TABLE `RENT` ADD CONSTRAINT `FK_BOOK_TO_RENT_1` FOREIGN KEY (
	`RE_BO_CODE`
)
REFERENCES `BOOK` (
	`BO_CODE`
);

ALTER TABLE `BOOK` ADD CONSTRAINT `FK_CATEGORY_TO_BOOK_1` FOREIGN KEY (
	`BO_CA_CODE`
)
REFERENCES `CATEGORY` (
	`CA_CODE`
);